# Generated by Django 4.2.5 on 2023-10-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coment',
        ),
        migrations.AddField(
            model_name='coments',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.post'),
            preserve_default=False,
        ),
    ]
