# Generated by Django 4.2.5 on 2023-09-29 07:37

import dingoapp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('num_of_g', models.IntegerField(verbose_name='Number of guests')),
                ('fone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('date', models.DateField(validators=[dingoapp.models.past_date_validator], verbose_name='Date')),
                ('time', models.TimeField(validators=[dingoapp.models.past_time_validator], verbose_name='Time')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ChefLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_level', models.CharField(max_length=150, verbose_name='Chef Level')),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=150, verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('about', models.TextField(verbose_name='About')),
                ('exsclusive', models.BooleanField(default=False, verbose_name='Exclusive')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Price')),
                ('picture', models.ImageField(default='.static/img/logo.png', upload_to='food/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ManyToManyField(to='dingoapp.category', verbose_name='Category')),
                ('tag', models.ManyToManyField(to='dingoapp.tagsmodel', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('picture', models.ImageField(upload_to='chef/', verbose_name='Picture')),
                ('fasebook', models.URLField(blank=True, max_length=150, null=True, verbose_name='Fasebook')),
                ('instagram', models.URLField(blank=True, max_length=150, null=True, verbose_name='Instagram')),
                ('x_tvit', models.URLField(blank=True, max_length=150, null=True, verbose_name='X')),
                ('skype', models.URLField(blank=True, max_length=150, null=True, verbose_name='Skype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dingoapp.cheflevel')),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
            },
        ),
    ]
